[package]
name = "ccj_postprocess"
version = "1.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
clap = "3.*"
relative-path = "*"
regex = "*"
rayon = "*"
